# Generated by Django 3.0.3 on 2020-04-07 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='audios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Date and Time')),
                ('listeners', models.IntegerField()),
                ('source', models.URLField()),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Audios',
            },
        ),
    ]
