# Generated by Django 3.0.3 on 2020-04-07 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_app', '0002_auto_20200407_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audios',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Date and Time'),
        ),
    ]
