# Generated by Django 3.0.3 on 2020-04-07 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='liveForcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('introduction', models.TextField(null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('watching', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
                ('source', models.URLField(max_length=500)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
