# Generated by Django 3.0.3 on 2020-04-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_forcast_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveforcast',
            name='introduction',
            field=models.TextField(blank=True, default=True),
        ),
    ]
