# Generated by Django 3.0.3 on 2020-04-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='elementarySchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonNumber', models.IntegerField()),
                ('Topic', models.CharField(max_length=100)),
                ('bibleText', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('comment', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Enlish Sunday School Lesson for Elementary',
            },
        ),
        migrations.CreateModel(
            name='englishSchoolA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonNumber', models.IntegerField()),
                ('Topic', models.CharField(max_length=100)),
                ('bibleText', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('comment', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Enlish Sunday Lesson for Adult',
            },
        ),
        migrations.CreateModel(
            name='englishSchoolI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonNumber', models.IntegerField()),
                ('Topic', models.CharField(max_length=100)),
                ('bibleText', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('comment', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Enlish Sunday Lesson for Intermediate',
            },
        ),
        migrations.CreateModel(
            name='frenchSchoolA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonNumber', models.IntegerField()),
                ('Topic', models.CharField(max_length=100)),
                ('bibleText', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('comment', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'French Sunday Lesson for Adult',
            },
        ),
        migrations.CreateModel(
            name='frenchSchoolI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonNumber', models.IntegerField()),
                ('Topic', models.CharField(max_length=100)),
                ('bibleText', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('comment', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'French Sunday Lesson for Intermediate',
            },
        ),
        migrations.CreateModel(
            name='yorubaSchoolA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonNumber', models.IntegerField()),
                ('Topic', models.CharField(max_length=100)),
                ('bibleText', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('comment', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Yoruba Sunday Lesson for Adult',
            },
        ),
        migrations.CreateModel(
            name='yorubaSchoolI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonNumber', models.IntegerField()),
                ('Topic', models.CharField(max_length=100)),
                ('bibleText', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('comment', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Yoruba Sunday Lesson for Intermediate',
            },
        ),
    ]
