# Generated by Django 3.0.3 on 2020-04-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday_school_app', '0002_auto_20200407_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='frenchschooli',
            name='Topic',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frenchschooli',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frenchschooli',
            name='bibleText',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frenchschooli',
            name='body',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frenchschooli',
            name='comment',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='frenchschooli',
            name='lessonNumber',
            field=models.IntegerField(),
        ),
    ]
