# Generated by Django 3.0.3 on 2020-04-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday_school_app', '0003_auto_20200407_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementaryschool',
            name='memoryVerse',
            field=models.CharField(default=True, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='englishschoola',
            name='memoryVerse',
            field=models.CharField(default=True, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='englishschooli',
            name='memoryVerse',
            field=models.CharField(default=True, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frenchschoola',
            name='memoryVerse',
            field=models.CharField(default=True, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frenchschooli',
            name='memoryVerse',
            field=models.CharField(default=True, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yorubaschoola',
            name='memoryVerse',
            field=models.CharField(default=True, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yorubaschooli',
            name='memoryVerse',
            field=models.CharField(default=True, max_length=250),
            preserve_default=False,
        ),
    ]
