# Generated by Django 3.0.3 on 2020-04-11 16:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday_school_app', '0004_auto_20200409_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementaryschool',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='englishschoola',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='englishschooli',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='frenchschoola',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='frenchschooli',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='yorubaschoola',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='yorubaschooli',
            name='comment',
        ),
        migrations.AlterField(
            model_name='elementaryschool',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='elementaryschool',
            name='memoryVerse',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='englishschoola',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='englishschoola',
            name='memoryVerse',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='englishschooli',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='englishschooli',
            name='memoryVerse',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='frenchschoola',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='frenchschoola',
            name='memoryVerse',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='frenchschooli',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='frenchschooli',
            name='memoryVerse',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='yorubaschoola',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='yorubaschoola',
            name='memoryVerse',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='yorubaschooli',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='yorubaschooli',
            name='memoryVerse',
            field=models.TextField(),
        ),
    ]
