# Generated by Django 3.0.3 on 2020-04-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday_school_app', '0006_englishschoola_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementaryschool',
            name='source',
            field=models.FileField(default=True, max_length=500, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='englishschooli',
            name='source',
            field=models.FileField(default=True, max_length=500, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frenchschoola',
            name='source',
            field=models.FileField(default=True, max_length=500, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frenchschooli',
            name='source',
            field=models.FileField(default=True, max_length=500, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yorubaschoola',
            name='source',
            field=models.FileField(default=True, max_length=500, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yorubaschooli',
            name='source',
            field=models.FileField(default=True, max_length=500, upload_to='media'),
            preserve_default=False,
        ),
    ]
