# Generated by Django 3.0.3 on 2020-04-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='displaySilder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discriptionTop', models.CharField(max_length=40)),
                ('discriptionBottom', models.CharField(max_length=100)),
                ('displayImage', models.ImageField(upload_to='images')),
            ],
        ),
    ]
