# Generated by Django 3.0.3 on 2020-04-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='setCountdownDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTitle', models.CharField(max_length=100)),
                ('eventDate', models.CharField(max_length=50)),
                ('eventDiscription', models.TextField()),
                ('endTimeMessage', models.CharField(max_length=100)),
                ('Active', models.BooleanField()),
            ],
        ),
    ]
