# Generated by Django 3.0.3 on 2020-04-04 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_setcountdowndate'),
    ]

    operations = [
        migrations.CreateModel(
            name='userType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createUserType', models.CharField(max_length=50, verbose_name='User Title')),
            ],
        ),
        migrations.CreateModel(
            name='urgentMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageTitle', models.CharField(max_length=50, verbose_name='Message Title')),
                ('date', models.TimeField(auto_now_add=True)),
                ('likeCount', models.IntegerField(verbose_name='Likes Count')),
                ('messageBody', models.TextField(verbose_name='Message Body')),
                ('UserTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.userType', verbose_name='User Title')),
            ],
        ),
    ]
