# Generated by Django 3.0.3 on 2020-04-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_urgentmessage_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgentmessage',
            name='Active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
