# Generated by Django 3.0.3 on 2020-04-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_urgentmessage_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urgentmessage',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
