# Generated by Django 3.0.3 on 2020-04-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200405_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='sermonUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500, verbose_name='Link to Video Source (e.g Youtube.)')),
                ('image', models.ImageField(upload_to='images', verbose_name='Image of a Scene During The Service')),
                ('sermonTitle', models.CharField(max_length=100, verbose_name='Sermon Title')),
                ('precherName', models.CharField(max_length=70, verbose_name='Officiating Minister')),
            ],
        ),
    ]
