# Generated by Django 3.0.3 on 2020-04-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_sermonupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgentmessage',
            name='userImage',
            field=models.ImageField(default=True, upload_to='images', verbose_name='User Passport(with any background'),
            preserve_default=False,
        ),
    ]
