# Generated by Django 3.0.3 on 2020-04-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_urgentmessage_userimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=150)),
                ('bible_ref', models.TextField()),
                ('date', models.CharField(max_length=50)),
                ('detail', models.TextField()),
            ],
        ),
    ]
