# Generated by Django 3.0.3 on 2020-04-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_subcribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcribe',
            name='email',
        ),
    ]
