# Generated by Django 3.0.3 on 2020-04-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_subcribe_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcribe',
            name='email',
            field=models.EmailField(default=True, max_length=254),
            preserve_default=False,
        ),
    ]
