# Generated by Django 3.0.3 on 2020-04-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_subcribe_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setcountdowndate',
            name='eventDate',
            field=models.DateField(),
        ),
    ]
