# Generated by Django 3.0.3 on 2020-04-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20200411_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaysilder',
            name='discriptionBottom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='displaysilder',
            name='discriptionTop',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
