# Generated by Django 3.0.3 on 2020-04-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20200411_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaysilder',
            name='title',
            field=models.CharField(default=True, max_length=150),
            preserve_default=False,
        ),
    ]
