# Generated by Django 3.0.3 on 2020-04-07 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='video',
            new_name='videos',
        ),
    ]
