# Generated by Django 3.0.3 on 2020-04-07 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_auto_20200407_0251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name_plural': 'Videos'},
        ),
    ]
