# Generated by Django 3.0.3 on 2020-04-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogTitle', models.CharField(max_length=50, verbose_name='Blog Tile')),
                ('blogSubtile', models.CharField(max_length=100, verbose_name='Subtitle[if any]')),
                ('blogBody', models.TextField(verbose_name='Body')),
                ('username', models.CharField(max_length=100)),
                ('userPicture', models.ImageField(upload_to='images')),
                ('aboutUser', models.TextField()),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
