# Generated by Django 3.0.3 on 2020-04-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='featuredImage',
            field=models.ImageField(default=True, upload_to='images', verbose_name='Featured Image'),
            preserve_default=False,
        ),
    ]
