# Generated by Django 3.0.3 on 2020-04-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_blog_featuredimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likeCount',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
