# Generated by Django 3.0.3 on 2020-04-10 23:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20200410_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='aboutUser',
            field=tinymce.models.HTMLField(),
        ),
    ]
