# Generated by Django 3.0.3 on 2020-04-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_auto_20200411_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogSubtile',
            field=models.TextField(blank=True, null=True, verbose_name='Subtitle[if any]'),
        ),
    ]
