# Generated by Django 3.0.3 on 2020-04-06 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userDuty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userDuty', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='testimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('introduction', models.CharField(default=False, max_length=2000)),
                ('featuredImage', models.ImageField(upload_to='images')),
                ('body', models.TextField()),
                ('username', models.CharField(max_length=50)),
                ('comment', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('userPicture', models.ImageField(default='static/images/default-avatar.png', upload_to='images')),
                ('UserDuty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_app.userDuty', verbose_name='Duty In The Church')),
            ],
        ),
    ]
