# Generated by Django 3.0.3 on 2020-04-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='testimony',
            new_name='testimony_s',
        ),
    ]
