# Generated by Django 3.0.3 on 2020-04-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0002_auto_20200406_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony_s',
            name='introduction',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
