# Generated by Django 3.0.3 on 2020-04-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0004_minister'),
    ]

    operations = [
        migrations.CreateModel(
            name='firstMinister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministerName', models.CharField(max_length=50, verbose_name="Minister's Name")),
                ('position', models.CharField(max_length=50, verbose_name='Duty in Church')),
                ('picture', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='secondMinister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministerName', models.CharField(max_length=50, verbose_name="Minister's Name")),
                ('position', models.CharField(max_length=50, verbose_name='Duty in Church')),
                ('picture', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='thirdMinister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministerName', models.CharField(max_length=50, verbose_name="Minister's Name")),
                ('position', models.CharField(max_length=50, verbose_name='Duty in Church')),
                ('picture', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='minister',
        ),
    ]
